### PR TITLE
Update to Cake 0.18.0

### PR DESCRIPTION
**Pull request by mabreuortega**
Minor changes to be able to use the tool against the latest Cake Core version.

### CODE REVIEW

**Comment by phil-scott-78** [comment]
Cool. This LGTM.  If you get a chance could you pull down the `0.2.0-ci0009` version and check it out? If it works for you I'll tag it and promote it to 0.2. 

I've honestly broken free from needing to use Mage so I don't have a good test for verifying the functionality in a real world scenario so I'd prefer someone that is using it for real work gives the thumbs up before I remove the prerelease from it :-)

**Comment by mabreuortega** [comment]
I'm using it to deploy a WinForm app without problems. Go ahead and do the tagging. Are you willing to publish this in the Cake Official Website?
If you know what to do, I can help!

**Comment by gep13** [comment]
>@mabreuortega said...
Are you willing to publish this in the Cake Official Website?  If you know what to do, I can help!

Are you referring to this [website](http://cakebuild.net/addins/) or the [cake-contrib organisation](https://github.com/cake-contrib)?

**Comment by mabreuortega** [comment]
yep

**Comment by gep13** [comment]
>@mabreuortega said...
yep

So which one?  I gave two options there 😄

**Comment by phil-scott-78** [comment]
Hey @gep13 , I'd be happy to transfer this over to the contrib organization. I'm not actively using Mage anymore so it would be a good opportunity for someone that is to pick up some maintenance.

**Comment by gep13** [comment]
@enkafan certainly happy to make this happen.  Ideally, we would still want you involved in the project to help answer any questions that might come up, but moving it into the organisation does make it easier for us to bring other people on-board to help out with maintenance.  If you would like to start that process, the easiest way to do it would be to transfer the repository over to my GitHub account (gep13) and from there, I can move it into the cake-contrib organisation.

**Comment by mabreuortega** [comment]
Cool thing this happening!

**Comment by gep13** [comment]
@enkafan just wanted to follow up to see if this is something that you are still interested in doing, thanks!

**Comment by phil-scott-78** [comment]
Definitely. My wife is leaving on a medical mission trip this weekend so
we've been scrambling getting her ready. But I'll knock it out tomorrow

**Comment by gep13** [comment]
>@enkafan said...
My wife is leaving on a medical mission trip this weekend so we've been scrambling getting her ready.

Wow! Exciting stuff!  Take your time, just wanted to touch base to see if it was still on the cards.

**Comment by phil-scott-78** [comment]
Alrighty, things have calmed down a bit and finally got around to this 😄 

Transfer should be pending. Thanks!

**Comment by gep13** [comment]
>@enkafan said...
Transfer should be pending. Thanks!

Nice one! Thank you!  I have moved the repo into the organisation.  I will sort out permissions, and CI, etc. later on.  Thanks again for moving this into the organisation, I truly believe it helps with the larger maintainability of Cake.

**Pull request merged**
